import dkd_test from 'node:test';
import dkd_assert from 'node:assert/strict';
import { JSDOM as dkd_JSDOM } from 'jsdom';
import { dkd_Game, dkd_escape } from '../game/dkd-ui.mjs';
import '../game/dkd-controller.mjs';
import { dkd_createGraph, dkd_defaultState, dkd_makeOrder, dkd_stepRun, dkd_canDeliver } from '../game/dkd-core.mjs';

// DOM interaction harness only; this does not substitute for a WebGL/device test.
function dkd_harness(dkd_profile = true) {
  const dkd_dom = new dkd_JSDOM('<!doctype html><html><body><canvas id="dkd-canvas"></canvas><main id="dkd-ui"></main><div id="dkd-modal"></div><div id="dkd-toast"></div></body></html>', { url: 'https://lastmile.test/' });
  Object.assign(globalThis, { window: dkd_dom.window, document: dkd_dom.window.document, localStorage: dkd_dom.window.localStorage, FormData: dkd_dom.window.FormData });
  const dkd_noop = () => {};
  const dkd_game = Object.create(dkd_Game.prototype); const dkd_state = dkd_defaultState();
  if (dkd_profile) dkd_state.dkd_profile = { dkd_name:'Demo Kurye',dkd_username:'Demo06',dkd_phone:'05550000000',dkd_company:'Test Express',dkd_photo:'' };
  Object.assign(dkd_game, { dkd_root: document.getElementById('dkd-ui'), dkd_state, dkd_career: dkd_state, dkd_test: null, dkd_graph: dkd_createGraph(), dkd_run: null, dkd_orders: [], dkd_orderBatch: 0, dkd_pageName: 'intro', dkd_routeMode: 'safe', dkd_input: { dkd_gas:false,dkd_brake:false,dkd_steer:0 }, dkd_audio: { dkd_start:dkd_noop,dkd_effect:dkd_noop,dkd_pause:dkd_noop,dkd_tracks:['Midnight Dispatch','Rain on Asphalt','Last Light','After the Signal','Home Before Dawn'],dkd_track:0 }, dkd_scene: { dkd_setMode:dkd_noop,dkd_refreshBrand:dkd_noop,dkd_resize:dkd_noop,dkd_buildBike:dkd_noop,dkd_setRoute:dkd_noop } });
  dkd_game.dkd_bind();
  return { dkd_game, dkd_dom, dkd_close: () => { clearTimeout(dkd_game.dkd_toastTimer); dkd_dom.window.close(); } };
}

dkd_test('all navigation pages render with Turkish labels and bounded content',()=>{const {dkd_game,dkd_close}=dkd_harness();try{for(const dkd_page of ['intro','register','brand','city','choose','home','career','phone','dispatch','garage','vault','contracts','messages','company','wallet','weather','navigation','reputation','daily','rankings','seasons','music','camera','settings','privacy','guide']){dkd_game.dkd_render(dkd_page);dkd_assert.ok(document.querySelector('#dkd-ui').textContent.length>10,dkd_page);dkd_assert.equal(document.querySelector('#dkd-ui').textContent.includes('undefined'),false,dkd_page);}dkd_game.dkd_render('vip','dkd_mira');dkd_game.dkd_render('chat','dkd_mira');dkd_game.dkd_render('call','dkd_mira');dkd_game.dkd_selectedOrder=dkd_game.dkd_orders[0];dkd_game.dkd_render('order');dkd_assert.match(document.querySelector('#dkd-ui').textContent,/KABUL ET/);}finally{dkd_close();}});
dkd_test('registration, identity and contract choices persist through real DOM events',()=>{const {dkd_game,dkd_dom,dkd_close}=dkd_harness(false);try{dkd_game.dkd_render('register');const dkd_values={dkd_name:'Demo Kurye',dkd_username:'Demo06',dkd_phone:'05550000000',dkd_company:'Test Express'};for(const[dkd_name,dkd_value]of Object.entries(dkd_values))document.querySelector(`[name="${dkd_name}"]`).value=dkd_value;document.querySelector('[name="dkd_local"]').checked=true;document.querySelector('[name="dkd_rules"]').checked=true;document.getElementById('dkd-register-form').dispatchEvent(new dkd_dom.window.Event('submit',{bubbles:true,cancelable:true}));dkd_assert.equal(dkd_game.dkd_pageName,'brand');dkd_assert.equal(dkd_game.dkd_state.dkd_profile.dkd_company,'Test Express');dkd_game.dkd_action('color:#51d8cf');dkd_game.dkd_action('city');dkd_assert.equal(document.querySelector('[data-dkd-action="choose"]').textContent.includes('ANKARA'),true);dkd_game.dkd_action('choose');dkd_game.dkd_action('prize:dkd_tablet');dkd_assert.equal(dkd_game.dkd_pageName,'choose');dkd_assert.equal(JSON.parse(localStorage.getItem('dkd_lastmile_v1')).dkd_career.dkd_prize,'dkd_tablet');}finally{dkd_close();}});
dkd_test('script injection strings in profiles and chats render as text',()=>{const {dkd_game,dkd_close}=dkd_harness();try{dkd_game.dkd_state.dkd_profile.dkd_company='<img src=x onerror=alert(1)>';dkd_game.dkd_render('home');dkd_assert.equal(document.querySelector('#dkd-ui img'),null);dkd_assert.match(document.querySelector('#dkd-ui h1').textContent,/<img/);dkd_assert.equal(dkd_escape('<script>"&'),'&lt;script&gt;&quot;&amp;');dkd_game.dkd_state.dkd_messages.push({dkd_from:'dkd_mira',dkd_text:'<script>alert(1)</script>'});dkd_game.dkd_render('chat','dkd_mira');dkd_assert.equal(document.querySelector('#dkd-ui script'),null);}finally{dkd_close();}});
dkd_test('demo test career stays isolated from the normal career',()=>{const {dkd_game,dkd_close}=dkd_harness();try{const dkd_before=JSON.stringify(dkd_game.dkd_career);dkd_game.dkd_action('test-enter');dkd_assert.equal(dkd_game.dkd_state.dkd_training,true);dkd_game.dkd_action('test-final');dkd_assert.equal(dkd_game.dkd_state.dkd_chapter,6);dkd_assert.equal(dkd_game.dkd_state.dkd_vip,'dkd_mira');dkd_assert.equal(JSON.stringify(dkd_game.dkd_career),dkd_before);dkd_game.dkd_action('test-exit');dkd_assert.equal(dkd_game.dkd_state.dkd_wallet,900);dkd_assert.equal(dkd_game.dkd_state.dkd_master,0);}finally{dkd_close();}});
dkd_test('drive, phone, pause, resume and delivery result integrate',()=>{const {dkd_game,dkd_close}=dkd_harness();try{dkd_game.dkd_selectedOrder=dkd_makeOrder(dkd_game.dkd_state,dkd_game.dkd_graph,571,'tutorial');dkd_game.dkd_startRun();dkd_assert.ok(document.getElementById('dkd-gas'));dkd_game.dkd_action('drive-phone');dkd_assert.equal(dkd_game.dkd_run.dkd_paused,true);dkd_game.dkd_action('garage');const dkd_wallet=dkd_game.dkd_state.dkd_wallet;dkd_game.dkd_action('buy-vehicle:dkd_electric');dkd_assert.equal(dkd_game.dkd_state.dkd_wallet,dkd_wallet);dkd_game.dkd_resume();dkd_assert.equal(dkd_game.dkd_run.dkd_paused,false);for(let dkd_frame=0;dkd_frame<15000;dkd_frame++){const dkd_stop=dkd_game.dkd_run.dkd_routeIndex>=dkd_game.dkd_run.dkd_route.dkd_nodes.length;dkd_stepRun(dkd_game.dkd_run,dkd_game.dkd_graph,{dkd_gas:!dkd_stop,dkd_brake:dkd_stop},1/60);if(dkd_canDeliver(dkd_game.dkd_run,dkd_game.dkd_graph))break;}dkd_game.dkd_updateHud();dkd_assert.equal(document.getElementById('dkd-deliver').style.display,'block');dkd_game.dkd_action('deliver');dkd_assert.equal(dkd_game.dkd_pageName,'result');dkd_assert.equal(dkd_game.dkd_state.dkd_tutorial,true);dkd_assert.match(document.querySelector('#dkd-ui').textContent,/DEMO KARİYERİNİ AÇ/);}finally{dkd_close();}});
dkd_test('scripted NPC response and purchases give visible feedback',()=>{const {dkd_game,dkd_dom,dkd_close}=dkd_harness();try{dkd_game.dkd_render('chat','dkd_mira');document.querySelector('[name="dkd_message"]').value='Gerçek ödül kazanır mıyım?';document.getElementById('dkd-chat-form').dispatchEvent(new dkd_dom.window.Event('submit',{bubbles:true,cancelable:true}));dkd_assert.match(document.querySelector('.dkd-chat-feed').textContent,/fiziksel ödül ve gerçek görüşme yok/);dkd_game.dkd_action('test-enter');dkd_game.dkd_action('buy-vehicle:dkd_125');dkd_assert.match(document.getElementById('dkd-modal').textContent,/Yeni aracın hazır/);dkd_assert.equal(dkd_game.dkd_state.dkd_equipped,'dkd_125');dkd_game.dkd_closeModal();dkd_game.dkd_action('upgrade:dkd_grip');dkd_assert.match(document.getElementById('dkd-modal').textContent,/Geliştirme tamamlandı/);dkd_assert.equal(dkd_game.dkd_state.dkd_upgrades.dkd_grip,1);}finally{dkd_close();}});
