import dkd_test from 'node:test';
import dkd_assert from 'node:assert/strict';
import * as dkd_core from '../game/dkd-core.mjs';
import { dkd_vehicles, dkd_weathers, dkd_packages, dkd_seasons } from '../game/dkd-data.mjs';
import { dkd_roadData } from '../game/data/dkd-roads.mjs';

const dkd_graph = dkd_core.dkd_createGraph();
function dkd_readyState() { const dkd_state = dkd_core.dkd_defaultState(); Object.assign(dkd_state, { dkd_profile: { dkd_name: 'Demo Kurye', dkd_username: 'Demo06', dkd_phone: '05550000000', dkd_company: 'Test Express', dkd_photo: '' }, dkd_tutorial: true, dkd_fullCareer: true, dkd_xp: 48000, dkd_wallet: 150000, dkd_master: 100, dkd_chapter: 6, dkd_storm: 10, dkd_deliveries: 100, dkd_ratingTotal: 500, dkd_vip: 'dkd_mira' }); return dkd_state; }
function dkd_drive(dkd_state, dkd_order, dkd_step = 1/60, dkd_traffic = false) { const dkd_run = dkd_core.dkd_createRun(dkd_state, dkd_graph, dkd_order, 'safe'); if (dkd_traffic) dkd_core.dkd_initTraffic(dkd_run, dkd_graph, 32); for (let dkd_frame = 0; dkd_frame < 900 / dkd_step; dkd_frame++) { const dkd_stop = dkd_run.dkd_routeIndex >= dkd_run.dkd_route.dkd_nodes.length; dkd_core.dkd_stepRun(dkd_run, dkd_graph, { dkd_gas: !dkd_stop, dkd_brake: dkd_stop, dkd_steer: 0 }, dkd_step); if (dkd_traffic) dkd_core.dkd_stepTraffic(dkd_run, dkd_graph, dkd_step); if (dkd_core.dkd_canDeliver(dkd_run, dkd_graph) || dkd_run.dkd_failed) break; } return dkd_run; }

dkd_test('real Ankara road package has complete references and provenance', () => { dkd_assert.equal(dkd_roadData.dkd_points.length, 1476); dkd_assert.equal(dkd_roadData.dkd_roads.length, 1562); dkd_assert.equal(dkd_roadData.dkd_license, 'ODbL-1.0'); dkd_assert.match(dkd_roadData.dkd_sourceSha256, /^[a-f0-9]{64}$/); for (const dkd_edge of dkd_graph.dkd_edges) { dkd_assert.ok(dkd_graph.dkd_points[dkd_edge.dkd_from]); dkd_assert.ok(dkd_graph.dkd_points[dkd_edge.dkd_to]); } });
dkd_test('one-way routing and road closure are respected', () => { const dkd_small = dkd_core.dkd_createGraph({ dkd_points: [[0,0],[10,0],[10,10]], dkd_roads: [{dkd_from:0,dkd_to:1,dkd_width:10,dkd_direction:1},{dkd_from:1,dkd_to:2,dkd_width:10,dkd_direction:0}] }); dkd_assert.deepEqual(dkd_core.dkd_pathfind(dkd_small,0,2).dkd_nodes,[0,1,2]); dkd_assert.equal(dkd_core.dkd_pathfind(dkd_small,2,0),null); dkd_assert.equal(dkd_core.dkd_pathfind(dkd_small,0,2,'safe',new Set([1])),null); });
dkd_test('all generated dispatch offers are reachable and deterministic', () => { const dkd_state=dkd_readyState(); for (let dkd_index=0;dkd_index<60;dkd_index++) { const dkd_first=dkd_core.dkd_makeOrder(dkd_state,dkd_graph,90210+dkd_index*31); const dkd_second=dkd_core.dkd_makeOrder(dkd_state,dkd_graph,90210+dkd_index*31); dkd_assert.deepEqual(dkd_first,dkd_second); dkd_assert.ok(dkd_first.dkd_safe.dkd_distance>0); for (let dkd_step=1;dkd_step<dkd_first.dkd_safe.dkd_nodes.length;dkd_step++) dkd_assert.ok(dkd_graph.dkd_adj[dkd_first.dkd_safe.dkd_nodes[dkd_step-1]].some(dkd_link=>dkd_link.dkd_to===dkd_first.dkd_safe.dkd_nodes[dkd_step])); } });
dkd_test('tutorial can be driven with real input simulation and rewards are idempotent', () => { const dkd_state=dkd_core.dkd_defaultState(); const dkd_order=dkd_core.dkd_makeOrder(dkd_state,dkd_graph,571,'tutorial'); const dkd_run=dkd_drive(dkd_state,dkd_order); dkd_assert.ok(dkd_core.dkd_canDeliver(dkd_run,dkd_graph)); const dkd_result=dkd_core.dkd_completeRun(dkd_state,dkd_run,dkd_graph); dkd_assert.ok(dkd_result.dkd_master); dkd_assert.equal(dkd_state.dkd_tutorial,true); dkd_assert.equal(dkd_state.dkd_deliveries,1); const dkd_wallet=dkd_state.dkd_wallet; dkd_assert.equal(dkd_core.dkd_completeRun(dkd_state,dkd_run,dkd_graph),null); dkd_assert.equal(dkd_state.dkd_wallet,dkd_wallet); });
dkd_test('delivery requires route checkpoints, arrival and a stopped vehicle', () => { const dkd_state=dkd_readyState(); const dkd_order=dkd_core.dkd_makeOrder(dkd_state,dkd_graph,571,'tutorial'); const dkd_run=dkd_core.dkd_createRun(dkd_state,dkd_graph,dkd_order); dkd_run.dkd_position=[...dkd_graph.dkd_points[dkd_order.dkd_to]]; dkd_assert.equal(dkd_core.dkd_canDeliver(dkd_run,dkd_graph),false); dkd_run.dkd_routeIndex=dkd_run.dkd_route.dkd_nodes.length; dkd_run.dkd_pendingStops=[]; dkd_run.dkd_speed=9; dkd_assert.equal(dkd_core.dkd_canDeliver(dkd_run,dkd_graph),false); dkd_run.dkd_speed=0; dkd_assert.equal(dkd_core.dkd_canDeliver(dkd_run,dkd_graph),true); });
dkd_test('pause freezes time, position and fuel',()=>{const dkd_state=dkd_readyState();const dkd_run=dkd_core.dkd_createRun(dkd_state,dkd_graph,dkd_core.dkd_makeOrder(dkd_state,dkd_graph,571,'tutorial'));dkd_run.dkd_paused=true;const dkd_before=JSON.stringify(dkd_run);for(let dkd_frame=0;dkd_frame<120;dkd_frame++)dkd_core.dkd_stepRun(dkd_run,dkd_graph,{dkd_gas:true},1/60);dkd_assert.equal(JSON.stringify(dkd_run),dkd_before);});
dkd_test('rain lengthens braking distance without increasing maximum speed',()=>{const dkd_state=dkd_readyState();const dkd_order=dkd_core.dkd_makeOrder(dkd_state,dkd_graph,571,'tutorial');const dkd_dry=dkd_core.dkd_createRun(dkd_state,dkd_graph,dkd_order);const dkd_wet=dkd_core.dkd_createRun(dkd_state,dkd_graph,dkd_order);dkd_dry.dkd_assist=false;dkd_wet.dkd_assist=false;dkd_wet.dkd_weather=dkd_weathers.find(dkd_item=>dkd_item.dkd_id==='dkd_rain');dkd_dry.dkd_speed=10;dkd_wet.dkd_speed=10;for(let dkd_frame=0;dkd_frame<25;dkd_frame++){dkd_core.dkd_stepRun(dkd_dry,dkd_graph,{dkd_brake:true},1/60);dkd_core.dkd_stepRun(dkd_wet,dkd_graph,{dkd_brake:true},1/60);}dkd_assert.ok(dkd_wet.dkd_distance>dkd_dry.dkd_distance);dkd_assert.ok(dkd_wet.dkd_speed>dkd_dry.dkd_speed);});
dkd_test('offroad permits a low-speed return instead of trapping the rider',()=>{const dkd_state=dkd_readyState();const dkd_run=dkd_core.dkd_createRun(dkd_state,dkd_graph,dkd_core.dkd_makeOrder(dkd_state,dkd_graph,571,'tutorial'));dkd_run.dkd_position[1]+=9;for(let dkd_frame=0;dkd_frame<60;dkd_frame++)dkd_core.dkd_stepRun(dkd_run,dkd_graph,{dkd_gas:true},1/60);dkd_assert.ok(dkd_run.dkd_speed>0);});
dkd_test('package damage and cold-chain quality have gameplay effects',()=>{const dkd_state=dkd_readyState();const dkd_order=dkd_core.dkd_makeOrder(dkd_state,dkd_graph,571,'tutorial');dkd_order.dkd_package='dkd_fragile';const dkd_run=dkd_core.dkd_createRun(dkd_state,dkd_graph,dkd_order);dkd_core.dkd_hit(dkd_run,1);dkd_assert.ok(dkd_run.dkd_damage>14);dkd_assert.ok(dkd_run.dkd_condition<100);dkd_run.dkd_order.dkd_package='dkd_frozen';dkd_run.dkd_weather=dkd_weathers.find(dkd_item=>dkd_item.dkd_id==='dkd_heat');for(let dkd_frame=0;dkd_frame<120;dkd_frame++)dkd_core.dkd_stepRun(dkd_run,dkd_graph,{},1/60);dkd_assert.ok(dkd_run.dkd_quality<100);});
dkd_test('insufficient funds, capacity and career gates cannot be bypassed through actions',()=>{const dkd_state=dkd_core.dkd_defaultState();dkd_assert.equal(dkd_core.dkd_buyVehicle(dkd_state,'dkd_van'),false);dkd_assert.equal(dkd_state.dkd_wallet,900);const dkd_order=dkd_core.dkd_makeOrder(dkd_state,dkd_graph,90247);dkd_assert.throws(()=>dkd_core.dkd_createRun(dkd_state,dkd_graph,dkd_order),/kariyerini/);dkd_state.dkd_fullCareer=true;dkd_order.dkd_package='dkd_oversized';dkd_assert.throws(()=>dkd_core.dkd_createRun(dkd_state,dkd_graph,dkd_order),/kapasitesi/);});
dkd_test('vehicle purchases, upgrades and final standardization',()=>{const dkd_state=dkd_readyState();dkd_assert.equal(dkd_core.dkd_buyVehicle(dkd_state,'dkd_sport'),true);dkd_assert.equal(dkd_core.dkd_buyVehicle(dkd_state,'dkd_sport'),false);dkd_state.dkd_upgrades={dkd_engine:5,dkd_grip:5,dkd_bag:5};const dkd_final=dkd_core.dkd_vehicleStats(dkd_state,true);dkd_assert.deepEqual(dkd_final,dkd_vehicles.find(dkd_vehicle=>dkd_vehicle.dkd_id==='dkd_125'));dkd_assert.ok(dkd_core.dkd_vehicleStats(dkd_state).dkd_speed>dkd_final.dkd_speed);});
dkd_test('the 100th actual Master earns exactly one VIP token',()=>{const dkd_state=dkd_readyState();dkd_state.dkd_master=99;dkd_state.dkd_tokens=0;dkd_state.dkd_vip=null;const dkd_run=dkd_drive(dkd_state,dkd_core.dkd_makeOrder(dkd_state,dkd_graph,571,'tutorial'));dkd_core.dkd_completeRun(dkd_state,dkd_run,dkd_graph);dkd_assert.equal(dkd_state.dkd_tokens,1);dkd_assert.equal(dkd_core.dkd_chooseVip(dkd_state,'dkd_mira'),true);dkd_assert.equal(dkd_core.dkd_chooseVip(dkd_state,'dkd_lara'),false);dkd_assert.equal(dkd_state.dkd_tokens,0);});
dkd_test('six VIP chapters and repeat VIP jobs remain playable',()=>{const dkd_state=dkd_readyState();dkd_state.dkd_chapter=0;for(let dkd_chapter=0;dkd_chapter<6;dkd_chapter++){const dkd_order=dkd_core.dkd_makeOrder(dkd_state,dkd_graph,6815+dkd_chapter*400,'vip');const dkd_run=dkd_drive(dkd_state,dkd_order);dkd_assert.ok(dkd_core.dkd_canDeliver(dkd_run,dkd_graph),`chapter ${dkd_chapter}`);dkd_core.dkd_completeRun(dkd_state,dkd_run,dkd_graph);dkd_assert.equal(dkd_state.dkd_chapter,dkd_chapter+1);}const dkd_repeat=dkd_drive(dkd_state,dkd_core.dkd_makeOrder(dkd_state,dkd_graph,9981,'vip-repeat'));dkd_core.dkd_completeRun(dkd_state,dkd_repeat,dkd_graph);dkd_assert.equal(dkd_state.dkd_chapter,6);dkd_assert.ok(dkd_state.dkd_daily.dkd_vip>=7);});
dkd_test('all four finals are reachable through every mandatory stop after events',()=>{for(let dkd_index=0;dkd_index<4;dkd_index++){const dkd_state=dkd_readyState();dkd_state.dkd_season=dkd_seasons[dkd_index].dkd_id;const dkd_order=dkd_core.dkd_makeOrder(dkd_state,dkd_graph,73117+dkd_index*1009,'final');dkd_assert.equal(dkd_order.dkd_stops.length,3);dkd_assert.ok(dkd_order.dkd_safe.dkd_distance>=2500);const dkd_run=dkd_drive(dkd_state,dkd_order,1/60,true);dkd_assert.ok(dkd_core.dkd_canDeliver(dkd_run,dkd_graph),`final ${dkd_index}`);dkd_assert.deepEqual(dkd_run.dkd_pendingStops,[]);dkd_assert.ok(dkd_run.dkd_signalMessaged);const dkd_result=dkd_core.dkd_completeRun(dkd_state,dkd_run,dkd_graph);dkd_assert.equal(dkd_result.dkd_audit.dkd_serverVerified,false);dkd_assert.equal(dkd_result.dkd_audit.dkd_prizeEligible,false);dkd_assert.equal(dkd_state.dkd_scores.length,1);dkd_assert.ok(dkd_result.dkd_score.dkd_total>=0&&dkd_result.dkd_score.dkd_total<=100000);}});
dkd_test('local audit flags teleportation, excess speed and recovery; never asserts server verification',()=>{const dkd_state=dkd_readyState();const dkd_run=dkd_drive(dkd_state,dkd_core.dkd_makeOrder(dkd_state,dkd_graph,571,'tutorial'));dkd_assert.equal(dkd_core.dkd_auditLocal(dkd_run).dkd_status,'LOCAL_CHECK_PASSED');dkd_run.dkd_telemetry[2][1]+=500;dkd_run.dkd_telemetry[2][4]=247/3.6;dkd_assert.equal(dkd_core.dkd_auditLocal(dkd_run).dkd_status,'LOCAL_INVALID');dkd_run.dkd_recovery=1;dkd_assert.ok(dkd_core.dkd_auditLocal(dkd_run).dkd_reasons.some(dkd_reason=>dkd_reason.includes('dönüş')));});
dkd_test('daily and streak calculations roll over and do not double-claim',()=>{const dkd_state=dkd_readyState();const dkd_now=Date.UTC(2026,8,7,12);dkd_state.dkd_streak.dkd_last='2026-09-06';dkd_state.dkd_streak.dkd_days=6;dkd_core.dkd_tickDay(dkd_state,dkd_now);dkd_assert.equal(dkd_state.dkd_streak.dkd_days,7);dkd_core.dkd_tickDay(dkd_state,dkd_now);dkd_assert.equal(dkd_state.dkd_streak.dkd_days,7);dkd_core.dkd_tickDay(dkd_state);Object.assign(dkd_state.dkd_daily,{dkd_clean:5,dkd_vip:3,dkd_distance:12000,dkd_rain:2,dkd_rated:1});const dkd_wallet=dkd_state.dkd_wallet;dkd_assert.equal(dkd_core.dkd_claimDaily(dkd_state),true);dkd_assert.equal(dkd_core.dkd_claimDaily(dkd_state),false);dkd_assert.equal(dkd_state.dkd_wallet,dkd_wallet+750);});
dkd_test('save restore validates settings, identifiers, profile and corrupt numeric fields',()=>{const dkd_raw=dkd_readyState();dkd_raw.dkd_wallet=-100;dkd_raw.dkd_equipped='unknown';dkd_raw.dkd_owned.push('unknown');dkd_raw.dkd_upgrades.dkd_engine=Infinity;dkd_raw.dkd_settings.dkd_quality='unsafe';dkd_raw.dkd_brand.dkd_color='url(javascript:bad)';dkd_raw.dkd_profile.dkd_photo='javascript:bad';const dkd_state=dkd_core.dkd_restoreState(JSON.parse(JSON.stringify(dkd_raw)));dkd_assert.equal(dkd_state.dkd_wallet,0);dkd_assert.equal(dkd_state.dkd_equipped,'dkd_city50');dkd_assert.equal(dkd_state.dkd_settings.dkd_quality,'balanced');dkd_assert.equal(dkd_state.dkd_profile.dkd_photo,'');dkd_assert.equal(dkd_state.dkd_upgrades.dkd_engine,0);dkd_assert.equal(dkd_state.dkd_brand.dkd_color,'#e4ff5e');dkd_assert.deepEqual(dkd_core.dkd_restoreState(null),dkd_core.dkd_defaultState());});
dkd_test('30 and 60 Hz simulation produce comparable tutorial outcomes',()=>{const dkd_state=dkd_readyState();const dkd_order=dkd_core.dkd_makeOrder(dkd_state,dkd_graph,571,'tutorial');const dkd_first=dkd_drive(dkd_state,dkd_order,1/60);const dkd_second=dkd_drive(dkd_state,dkd_order,1/30);dkd_assert.ok(dkd_core.dkd_canDeliver(dkd_second,dkd_graph));dkd_assert.ok(Math.abs(dkd_first.dkd_elapsed-dkd_second.dkd_elapsed)<2);});
dkd_test('dynamic traffic follows legal graph links and time freezes when paused',()=>{const dkd_state=dkd_readyState();const dkd_run=dkd_core.dkd_createRun(dkd_state,dkd_graph,dkd_core.dkd_makeOrder(dkd_state,dkd_graph,90247));dkd_core.dkd_initTraffic(dkd_run,dkd_graph,32);for(let dkd_frame=0;dkd_frame<600;dkd_frame++)dkd_core.dkd_stepTraffic(dkd_run,dkd_graph,1/60);for(const dkd_car of dkd_run.dkd_traffic)dkd_assert.ok(dkd_graph.dkd_adj[dkd_car.dkd_from].some(dkd_link=>dkd_link.dkd_to===dkd_car.dkd_to));dkd_run.dkd_paused=true;const dkd_before=JSON.stringify(dkd_run.dkd_traffic);dkd_core.dkd_stepTraffic(dkd_run,dkd_graph,1);dkd_assert.equal(JSON.stringify(dkd_run.dkd_traffic),dkd_before);});

dkd_test('malformed imported lists and empty ghost recordings cannot crash game screens',()=>{const dkd_raw=dkd_readyState();Object.assign(dkd_raw,{dkd_reviews:[null,{},'bad'],dkd_messages:[null,{dkd_from:'missing'}],dkd_scores:[{},null,{dkd_score:'bad'}],dkd_transactions:[null,{}],dkd_completedRuns:[null,{}],dkd_ghost:{dkd_frames:[]},dkd_chapter:999,dkd_garage:999});const dkd_state=dkd_core.dkd_restoreState(dkd_raw);for(const dkd_key of ['dkd_reviews','dkd_messages','dkd_scores','dkd_transactions','dkd_completedRuns'])dkd_assert.deepEqual(dkd_state[dkd_key],[]);dkd_assert.equal(dkd_state.dkd_ghost,null);dkd_assert.equal(dkd_state.dkd_chapter,6);dkd_assert.equal(dkd_state.dkd_garage,3);});
